### ISSUE TITLE
Updating the logging configuration for ExpressStepFunction does not trigger a redeploy

### ISSUE THREAD

**Issue by tvanhens** [functionless/functionless#441] opened 2022-08-25 21:33 UTC
Steps to reproduce:

1. Deploy an `ExpressStepFunction` with no logging configuration
2. Add a logging configuration.
3. Re-deploy

Expected outcome:

The Step Function should be updated with the new logging config.

Actual outcome:

The logging configuration remains unmodified.

**Comment by thantos** [comment] 2022-08-25 22:30
I believe the root cause is fixed in #425, though it may be a while before that PR is merged, should hoist it to it's own PR.

here: https://github.com/functionless/functionless/pull/425/files#diff-961ed18b565d502c0f3e3673413b522c59ba0121e9bec07aca2807cf73309addL1584-R1586

:(

**Comment by thantos** [comment] 2022-08-25 22:30
Root cause: no props are being passed at all :/

**Comment by tvanhens** [comment] 2022-08-25 22:36
Ah array lookup, a TypeScript types fan's worst enemy.

**Comment by thantos** [comment] 2022-08-25 22:39
And me being lazy and not writing a test for props...

**Comment by thantos** [comment] 2022-08-25 22:52
> Ah array lookup, a TypeScript types fan's worst enemy.

And using `as` in typescript.

**Comment by tvanhens** [comment] 2022-08-25 22:55
OK compiler just pretend it looks like a duck.

Really wish they would have made that a proper coercion operator, adding a check and returning the type or null like in most sane typed languages.

**Closed** 2022-08-26 18:38 UTC
Labels: step-functions

**Comment by thantos** [comment] 2022-08-28 04:05
@tvanhens you can try `=== undefined` now once 0.21.19 releases.
