### ISSUE TITLE
Is it possible to use a `Function` as a lambda authorizer?

### ISSUE THREAD

**Issue by volkanunsal** [functionless/functionless#264] opened 2022-06-17 01:02 UTC
Here is what I'm trying to do:

```ts
const defaultAuthFunction0 = new Function(
  this,
  'LambdaAuthorizer',
  {
    memorySize: 256,
    timeout: Duration.minutes(1),
    logRetention: 14
  },
  async () => ({isAuthorized: true})
);
const defaultAuthFunction = defaultAuthFunction0.resource;


const api = new appsync.GraphqlApi(this, 'API', {
  name: 'API',
  schema,
  authorizationConfig: {
    defaultAuthorization: {
      authorizationType: appsync.AuthorizationType.LAMBDA,
      lambdaAuthorizerConfig: {
        handler: defaultAuthFunction,
      },
    },
  },
  xrayEnabled: true,
  logConfig: {
    fieldLogLevel: FieldLogLevel.ALL,
  },
});
```

But I'm getting a `SynthError`

```
SynthError: Expected input function to Function to be compiled by Functionless. Make sure you have the Functionless compiler plugin configured correctly.
```

**Comment by thantos** [comment] 2022-06-17 01:21
No reason that shouldn't work. `npx ts-patch check` shows that it's installed?

**Comment by thantos** [comment] 2022-06-17 01:26
`npx ts-patch install -s`

You may need to make an arbitrary change in the file or delete the .js output and re-run `yarn build` or `yarn watch`.

**Comment by volkanunsal** [comment] 2022-06-17 01:52
I think i simplified the example too much. The actual lambda code is slightly different:

```ts
const lambdaAuth: AuthHandler = async (c) => {
  const apiKey = c.authorizationToken || '';
  if (!apiKey) return getAuth(undefined, apiKey);

  const res = DDB.query({
    query: {
      expression: 'pk = :pk',
      expressionValues: {
        ':pk': { S: `API#${apiKey}` },
      },
    },
    index: 'GSI1',
    limit: 1,
  });

  return getAuth(res.items[0], apiKey);
};
```

And this is the getAuth function, which is imported from another file.

```ts
function getAuth(item: IAccount | void, apiKey: string) {
  let context: Record<string, any> = {};

  if (item?.entityType === 'Account') {
    const accountId = item.Id;
    context.accountId = accountId;
    context.apiKey = apiKey;
  }

  return {
    isAuthorized: true,
    resolverContext: context,
    deniedFields: [],
  };
}

```

I've tried removing both `getAuth` and `DDB` query separately, but both cases failed.

**Comment by volkanunsal** [comment] 2022-06-17 02:07
I think I narrowed down the root cause to using the function argument.

**Comment by thantos** [comment] 2022-06-17 02:19
ahh, yeah, we don't currently support referencing closures, they must be inline.

Mostly because we discover and replace inline.

We have an issue somewhere to fix that and are actively working on it.

**Comment by sam-goodwin** [comment] 2022-06-17 02:20
In your example, is DDB a reference to a Table? The Table.query function is only supported by appsync. Be sure to use $AWS in Lambda 

```ts
$AWS.DynamoDB.Query({
  TableName: DDB
});
```

**Comment by volkanunsal** [comment] 2022-06-17 02:29
Got it to work. Thanks you both for the feedback. I'll close this issue if you already have a tracking issue for the closure issue.

**Comment by sam-goodwin** [comment] 2022-06-17 02:30
> Got it to work. Thanks you both for the feedback. I'll close this issue if you already have a tracking issue for the closure issue.

Thank you for your patience as we work through these early bugs! The next version of the closure will bring simplifications and should remove the current limitations.

**Comment by sam-goodwin** [comment] 2022-06-17 02:31
One feature we are super excited about is higher order functions - the ability to pass function closures around and have IAM policies automatically inferred from them.

**Comment by sam-goodwin** [comment] 2022-06-17 02:41
Another thing to solve here is to decouple from appsync alpha and provide our own graphql constructs that integrate natively with Function

**Comment by volkanunsal** [comment] 2022-06-17 03:04
I couldn't quite get it to work as a lambda authorizer. While it compiles, once it's deployed, my requests are rejected with `BadRequestException`, which indicates a malformed request. But there is nothing in the logs. Using a `NodejsFunction` doesn't cause this issue.

**Comment by sam-goodwin** [comment] 2022-06-17 03:18
Bummer. Will see if we can reproduce that error. 

In the meantime, what does the lambda's code look like in the console? Is it valid Js?

**Comment by volkanunsal** [comment] 2022-06-17 03:37
Here it is:

```js

var __integrationPrewarms = [__f1];
var __preWarmContext_proto = {};
Object.defineProperty(__f2, "prototype", { value: __preWarmContext_proto });
Object.defineProperty(__preWarmContext_proto, "constructor", { configurable: true, writable: true, value: __f2 });
Object.defineProperty(__preWarmContext_proto, "get", { configurable: true, writable: true, value: __f3 });
Object.defineProperty(__preWarmContext_proto, "getOrInit", { configurable: true, writable: true, value: __f4 });
var __preWarmContext = Object.create(__preWarmContext_proto);
var __preWarmContext_props = {clientConfigRetriever: undefined};
__preWarmContext.props = __preWarmContext_props;
var __preWarmContext_cache = {};
__preWarmContext.cache = __preWarmContext_cache;
var __getAuth_1 = {getAuth: __getAuth};
var __DDB = {};
__DDB.functionlessKind = "Table";
__DDB.kind = "Table";
var __DDB_getItem = {};
__DDB_getItem.kind = "Table.getItem";
__DDB_getItem.unhandledContext = __f6;
var __DDB_getItem_native = {call: undefined, preWarm: undefined};
__DDB_getItem.native = __DDB_getItem_native;
__DDB.getItem = __DDB_getItem;
var __DDB_putItem = {};
__DDB_putItem.kind = "Table.putItem";
__DDB_putItem.unhandledContext = __f7;
var __DDB_putItem_native = {call: undefined, preWarm: undefined};
__DDB_putItem.native = __DDB_putItem_native;
__DDB.putItem = __DDB_putItem;
var __DDB_updateItem = {};
__DDB_updateItem.kind = "Table.updateItem";
__DDB_updateItem.unhandledContext = __f8;
var __DDB_updateItem_native = {call: undefined, preWarm: undefined};
__DDB_updateItem.native = __DDB_updateItem_native;
__DDB.updateItem = __DDB_updateItem;
var __DDB_deleteItem = {};
__DDB_deleteItem.kind = "Table.deleteItem";
__DDB_deleteItem.unhandledContext = __f9;
var __DDB_deleteItem_native = {call: undefined, preWarm: undefined};
__DDB_deleteItem.native = __DDB_deleteItem_native;
__DDB.deleteItem = __DDB_deleteItem;
var __DDB_query = {};
__DDB_query.kind = "Table.query";
__DDB_query.unhandledContext = __f10;
var __DDB_query_native = {call: undefined, preWarm: undefined};
__DDB_query.native = __DDB_query_native;
__DDB.query = __DDB_query;
__DDB.tableName = process.env.env__functionless206;
__DDB.tableArn = process.env.env__functionless204;
var __DDB_native = {call: undefined, preWarm: undefined};
__DDB.native = __DDB_native;

function __f1(__0) {
  return (function() {
    with({ function_1: require("functionless/lib/function.js") }) {

return function /*preWarm*/(prewarmContext) {
                        prewarmContext.getOrInit(function_1.PrewarmClients.DYNAMO);
                    };

    }
  }).apply(undefined, undefined).apply(this, arguments);
}

function __f2(__0) {
  return (function() {
    with({  }) {

return function /*constructor*/(props) {
        this.props = props;
        this.cache = {};
    };

    }
  }).apply(undefined, undefined).apply(this, arguments);
}

function __f3(__0) {
  return (function() {
    with({  }) {

return function /*get*/(key) {
        return this.cache[key];
    };

    }
  }).apply(undefined, undefined).apply(this, arguments);
}

function __f4(__0) {
  return (function() {
    with({  }) {

return function /*getOrInit*/(client) {
        if (!this.cache[client.key]) {
            this.cache[client.key] = client.init(client.key, this.props);
        }
        return this.cache[client.key];
    };

    }
  }).apply(undefined, undefined).apply(this, arguments);
}

function __getAuth(__0, __1) {
  return (function() {
    with({ getAuth: __getAuth }) {

return function /*getAuth*/(item, apiKey) {
    let context = {};
    if ((item === null || item === void 0 ? void 0 : item.entityType) === 'Account') {
        const accountId = item.Id;
        context.accountId = accountId;
        context.apiKey = apiKey;
    }
    return {
        isAuthorized: true,
        resolverContext: context,
        deniedFields: [],
    };
};

    }
  }).apply(undefined, undefined).apply(this, arguments);
}

function __f6(__0, __1) {
  return (function() {
    with({ vtl_1: require("functionless/lib/vtl.js") }) {

return function /*unhandledContext*/(kind, contextKind) {
                throw new Error(`${kind} is only allowed within a '${vtl_1.VTL.ContextName}' context, but was called within a '${contextKind}' context.`);
            };

    }
  }).apply(undefined, undefined).apply(this, arguments);
}

function __f7(__0, __1) {
  return (function() {
    with({ vtl_1: require("functionless/lib/vtl.js") }) {

return function /*unhandledContext*/(kind, contextKind) {
                throw new Error(`${kind} is only allowed within a '${vtl_1.VTL.ContextName}' context, but was called within a '${contextKind}' context.`);
            };

    }
  }).apply(undefined, undefined).apply(this, arguments);
}

function __f8(__0, __1) {
  return (function() {
    with({ vtl_1: require("functionless/lib/vtl.js") }) {

return function /*unhandledContext*/(kind, contextKind) {
                throw new Error(`${kind} is only allowed within a '${vtl_1.VTL.ContextName}' context, but was called within a '${contextKind}' context.`);
            };

    }
  }).apply(undefined, undefined).apply(this, arguments);
}

function __f9(__0, __1) {
  return (function() {
    with({ vtl_1: require("functionless/lib/vtl.js") }) {

return function /*unhandledContext*/(kind, contextKind) {
                throw new Error(`${kind} is only allowed within a '${vtl_1.VTL.ContextName}' context, but was called within a '${contextKind}' context.`);
            };

    }
  }).apply(undefined, undefined).apply(this, arguments);
}

function __f10(__0, __1) {
  return (function() {
    with({ vtl_1: require("functionless/lib/vtl.js") }) {

return function /*unhandledContext*/(kind, contextKind) {
                throw new Error(`${kind} is only allowed within a '${vtl_1.VTL.ContextName}' context, but was called within a '${contextKind}' context.`);
            };

    }
  }).apply(undefined, undefined).apply(this, arguments);
}

function __cleanDDTypes(__0) {
  return (function() {
    with({ cleanDDTypes: __cleanDDTypes }) {

return function /*cleanDDTypes*/(itemAttrs) {
        return Object.fromEntries(Object.entries(itemAttrs.AccountEmail).map((v) => [
            v[0],
            Object.values(v[1])[1],
        ]));
    };

    }
  }).apply(undefined, undefined).apply(this, arguments);
}

function __f5(__0) {
  return (function() {
    with({ getAuth_1: __getAuth_1, functionless_2: require("functionless/lib/index.js"), DDB: __DDB, preWarmContext_1: __preWarmContext, cleanDDTypes: __cleanDDTypes }) {

return async (c) => {
        var _a;
        const apiKey = c.authorizationToken || '';
        console.log('>>>>>>>>>>>> mkFuncAuth: c: ', c);
        if (!apiKey)
            return (0, getAuth_1.getAuth)();
        const items = ((_a = (await functionless_2.$AWS.DynamoDB.Query.native.call([{
                TableName: DDB,
                KeyConditionExpression: 'pk = :pk',
                ExpressionAttributeValues: {
                    ':pk': { S: `API#${apiKey}` },
                },
                IndexName: 'GSI1',
                Limit: 1,
            }], preWarmContext_1))) === null || _a === void 0 ? void 0 : _a.Items) || [];
        const item = items[0];
        console.log('>>>>>>>>>>>> mkFuncAuth: item: ', item);
        if (!item)
            return (0, getAuth_1.getAuth)(undefined, apiKey);
        const account = cleanDDTypes(item);
        return (0, getAuth_1.getAuth)(account, apiKey);
    };

    }
  }).apply(undefined, undefined).apply(this, arguments);
}

function __f0() {
  return (function() {
    with({ integrationPrewarms: __integrationPrewarms, preWarmContext: __preWarmContext, func: __f5 }) {

return () => {
            integrationPrewarms.forEach((i) => i === null || i === void 0 ? void 0 : i(preWarmContext));
            return func;
        };

    }
  }).apply(undefined, undefined).apply(this, arguments);
}

exports.handler = __f0();
```

**Comment by thantos** [comment] 2022-06-17 04:42
Running some tests

Worked, or rather the test returned the right object.

* Importing the getAuth method from outside.
* Using table with GSI
* Using `$AWS.DynamoDB.Query`

```ts
  test.only(
    "authorizer",
    (parent) => {
      const table = new Table<IAccount, "Id">(parent, "table", {
        partitionKey: {
          name: "Id",
          type: AttributeType.STRING,
        },
      });

      (table.resource as aws_dynamodb.Table).addGlobalSecondaryIndex({
        indexName: "GSI1",
        partitionKey: {
          name: "pk",
          type: AttributeType.STRING,
        },
      });

      const Query = $AWS.DynamoDB.Query;

      return new Function(
        parent,
        "function",
        localstackClientConfig,
        async (c) => {
          const apiKey = c.authorizationToken || "";
          if (!apiKey) return getAuth(undefined, apiKey);

          const res = Query({
            TableName: table,
            KeyConditionExpression: "pk = :pk",
            ExpressionAttributeValues: {
              ":pk": { S: `API#${apiKey}` },
            },
            IndexName: "GSI1",
            Limit: 1,
          });

          const item = res.Items?.[0];
          if (item) {
            const account: IAccount = {
              Id: item.Id.S,
              pk: item.pk.S,
              entityType: item.entityType?.S,
            };

            return getAuth(account, apiKey);
          }

          throw new Error("Nothing!");
        }
      );
    },
    {
      isAuthorized: true,
      resolverContext: {},
      deniedFields: [],
    },
    {}
  );
```

**Comment by thantos** [comment] 2022-06-17 04:42
Going to try on aws now.

**Comment by thantos** [comment] 2022-06-17 06:34
Hey @volkanunsal here is a working example using `Function` as an AppSync authorizer.

https://github.com/functionless/functionless/commit/816b96be5e01a348bea8aa42aace8e13e026a591

With account

![image](https://user-images.githubusercontent.com/289213/174239231-45b743b7-6c23-4879-aa6c-75c8c3546455.png)

Without account

![image](https://user-images.githubusercontent.com/289213/174239285-22ff5904-4f19-4ce5-9452-3061aabbce80.png)

Missing token

![image](https://user-images.githubusercontent.com/289213/174239335-98731155-497b-455f-ae7b-fa6b1fc9a3e6.png)

**Comment by sam-goodwin** [comment] 2022-06-17 06:36
This doesn't look right? 

<img width="228" alt="image" src="https://user-images.githubusercontent.com/38672686/174239777-1bca9bef-83c0-40df-841b-e00ce6cd5568.png">

**Comment by thantos** [comment] 2022-06-17 06:36
I am just calling toString on the requestContext map. Would definitely clean up the output for a real use case.

**Comment by thantos** [comment] 2022-06-17 06:39
1. Request from appsync to lambda for authorization
2. The auth token is required else 401
3. Lambda looks up the auth token in dynamo using the GSI.
4. If a record is found, the account ID and auth token are returned
5. App sync resolver returns a stringified version of the `identity.requesContext`, which is the data that the lambda returned.

**Comment by volkanunsal** [comment] 2022-06-17 10:37
Curious... the working example looks pretty much like my code. I can't tell why it works for you and not for me. I'm including the auth token as well. Here is my curl:

```
curl -XPOST -H "Content-Type:application/graphql" -H "Authorization:foobar" -d '{"query": "query MyQuery { account { AccountEmail } }"}' $URL
```

**Comment by thantos** [comment] 2022-06-17 13:20
```console
$ curl -XPOST -H "Content-Type:application/graphql" -H "Authorization:bah" -d '{"query": "query Query { something }"}' $URL

$ {"data":{"something":"{accountId=Account1, apiKey=bah}"}}
```

**Comment by thantos** [comment] 2022-06-17 13:22
You said there is nothing in the logs, is there anything in the appsync logs?

**Comment by volkanunsal** [comment] 2022-06-17 13:27
Yeah, there are 3 log entries in AppSync logs. The status code on the first one is 400, which makes me think that the request never reaches the lambda. Not sure why though. If i swap the `NodejsFunction` in its place, it works perfectly. I'm not changing the configuration of AppSync anywhere. 

```
{
    "logType": "RequestSummary",
    "requestId": "5619f379-04ed-456f-a065-089470bbae28",
    "graphQLAPIId": "rgog43k3hre73cvn64t443pjfm",
    "statusCode": 400,
    "latency": 32831606
}
```

**Comment by volkanunsal** [comment] 2022-06-17 14:09
I wonder if it's a permission issue.

**Comment by thantos** [comment] 2022-06-17 14:23
CDK should automatically add permissions onto the function when used as a handler, but good to check in the configuration > permissions of the lambda to ensure the appsync service principal can invoke.

Looks like this is a known issue: https://github.com/aws/aws-cdk/issues/19239

and.. was fixed in 2.28, which I just upgraded to :-)

https://github.com/aws/aws-cdk/commit/61764009648a4602ffa403adda903442c48c45df

**Comment by volkanunsal** [comment] 2022-06-17 14:25
Oh ok. Yeah, I added a ServicePrincipal and got around the 400 error. Now I'm getting a 500 error. Progress. 🙂

**Comment by thantos** [comment] 2022-06-17 14:48
Interesting...

Your is trying to import from functionless

```ts
function __f1(__0) {
  return (function() {
    with({ function_1: require("functionless/lib/function.js") }) {

return function /*preWarm*/(prewarmContext) {
                        prewarmContext.getOrInit(function_1.PrewarmClients.DYNAMO);
                    };

    }
  }).apply(undefined, undefined).apply(this, arguments);
}
```

* How are you importing functionless into your file? mine: `import { $AWS, Table, Function, AppsyncResolver, ITable } from "functionless";`
* Does your bundle end up with any imports? We are probably missing adding node_modules to the bundle.


while mine lined the function:

```ts
function __f1(__0) {
  return (function() {
    with({ function_1: __function_1 }) {

return function /*preWarm*/(prewarmContext) {
                        prewarmContext.getOrInit(function_1.PrewarmClients.DYNAMO);
                    };

    }
  }).apply(undefined, undefined).apply(this, arguments);
}
```

**Comment by sam-goodwin** [comment] 2022-06-17 18:07
> I can recreate the issue with a project that is not using yarn link for functionless

Anyway to have a test for this?

**Comment by thantos** [comment] 2022-06-19 04:46
> > I can recreate the issue with a project that is not using yarn link for functionless
> 
> Anyway to have a test for this?

Yeah, I added an alias to force functionless to look like an external dependency. Should be testing like it was installed in another library. Interestingly it also uncovers some type issues.

**Closed** 2022-06-21 02:30 UTC
